# Generated by Django 3.2.7 on 2021-10-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=300)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_time', to='main.room')),
            ],
        ),
    ]
